kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: auth-webflux
  name: auth-webflux-env
data:
  NAMESPACE_NAME: {{ .Release.Namespace | quote }}
  ISTIOD_ADDR: {{ .Values.istiod_addr | quote }}
  POLLING_TIME: {{ .Values.default_polling_time | quote }}