kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: auth-webflux
  name: auth-webflux-env
data:
  NAMESPACE_NAME: {{ .Release.Name }}
  ISTIOD_ADDR: {{ .Values.istiod-addr }}
  POLLING_TIME: {{ .Values.default-polling-time }}