kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: istio-consumer
  name: istio-consumer-env
data:
  NAMESPACE_NAME: {{ .Release.Namespace | quote }}
  ISTIOD_ADDR: {{ .Values.istiod_addr | quote }}
  POLLING_TIME: {{ .Values.default_polling_time | quote }}