image_auth_mvc:
  repository: registry.cn-shenzhen.aliyuncs.com/sca-demo/auth-demo-mvc
  tag: develop
image_auth_webflux:
  repository: registry.cn-shenzhen.aliyuncs.com/sca-demo/auth-demo-webflux
  tag: develop
image_default_provider_version:
  repository: registry.cn-shenzhen.aliyuncs.com/sca-demo/default-provider-version-example
  tag: develop
image_provider_version:
  repository: registry.cn-shenzhen.aliyuncs.com/sca-demo/provider-version-example
  tag: develop
image_istio_consumer:
  repository: registry.cn-shenzhen.aliyuncs.com/sca-demo/istio-consumer-example
  tag: develop
image_nacos_server:
  repository: nacos/nacos-server
  tag: v2.1.0
istiod_addr: istiod.istio-system.svc.cluster.local
default_polling_time: 60